Depl-218574 Synchronize monitoring config with trackor.onevizion.com Depl-218574-104586

diff --git a/setup/templates/cron-launcher-python.template b/setup/templates/cron-launcher-python.template
--- a/setup/templates/cron-launcher-python.template
+++ b/setup/templates/cron-launcher-python.template
@@ -39,3 +39,8 @@ fi
 
 echo "[$(date)] Started" >> "$SERVICE_OUT"
 python3 "$PYTHON_SCRIPT_PATH" >>"$SERVICE_OUT" 2>&1
+
+EXIT_CODE="$?"
+if [ "$EXIT_CODE" -gt 0 ]; then
+    echo "[$(date)] Failed with exit code $EXIT_CODE" >> "$SERVICE_OUT"
+fi
